[task_08] Лабораторная работы №8
brstu/OOTPISP-2023 pull request #103
Opened 2023-11-20 10:48 UTC by 11ALX11

2023-11-20 13:47 UTC, NogameNo-life requested changes
Код в блоках, а не картинками, а лучше вообще их не вставлять, смысл если его можно посмотреть в самом файле. .gitignore удалить

2023-11-20 20:23 UTC, 11ALX11 commented
Ну в отчет что-то надо вставить)

А когда лаба по паттернам проектирования, тут как бы только и показывать, как код написал

2023-11-21 07:04 UTC, 11ALX11 commented
0_0  codacy отлагал

2023-11-22 08:28 UTC, NogameNo-life approved these changes

2023-11-22 08:29 UTC, merged