[task_04] Lab 04
brstu/OOTPISP-2023 pull request #114
Opened 2023-11-21 19:21 UTC by Ian3707

2023-12-04 10:31 UTC, Pandusss approved these changes
Всё гуд!

2023-12-05 07:17 UTC, Nenroin reviewed
И опять же не работает....
![изображение_2023-12-05_101725605](https://github.com/brstu/OOTPISP-2023/assets/96544191/7e033f08-7bed-4553-b7a6-91e1e2aa8d91)

2023-12-05 17:36 UTC, Nenroin approved these changes
Согласен, все работает

2023-12-22 05:24 UTC, NogameNo-life requested changes
Зачем App.config?

2023-12-22 11:19 UTC, Ian3707 commented
> Зачем App.config?

Ну изначально именно эта лаба без App.config не запускалась, но уже починил

2023-12-23 18:02 UTC, NogameNo-life commented
Тогда надо убрать App.Config и изменения в .gitignore

2023-12-23 18:42 UTC, Ian3707 commented
> Тогда надо убрать App.Config и изменения в .gitignore

Так я это и сделал, последний коммит (repairgitignore) перед комментарием

2023-12-27 13:38 UTC, NogameNo-life approved these changes

2023-12-27 13:39 UTC, merged