[task_07] Lab 07
brstu/OOTPISP-2023 pull request #116
Opened 2023-11-22 16:16 UTC by dimasolyshko

2023-11-22 16:33 UTC, 11ALX11 requested changes

2023-11-22 16:33 UTC, 11ALX11 commented on trunk/PO-9_210668/task_07/README.md
> +- Реализовал движение по траектории синусоиды y = asin(x+b)
Используй математические формулы

```suggestion
- Реализовал движение по траектории синусоиды $$y = asin(x+b)$$
```

2023-11-22 16:33 UTC, 11ALX11 commented on trunk/PO-9_210668/task_07/README.md
> +![gif](images/ZDES_MOGLA_BYT_VASHA_REKLAMA.gif)
:+1:

2023-11-22 16:42 UTC, 11ALX11 approved these changes

2023-11-23 06:46 UTC, NogameNo-life approved these changes

2023-11-24 05:59 UTC, merged