[task_02] lab2
brstu/OOTPISP-2023 pull request #135
Opened 2023-11-25 15:45 UTC by Nenroin

2023-11-25 16:17 UTC, 11ALX11 requested changes
Андреееееей, забыл исходники в /src перекинуть, у тебя сейчас всё вместе в task_02.

А так проект запускается :+1:

2023-11-25 16:26 UTC, 11ALX11 approved these changes

2023-11-25 18:37 UTC, NogameNo-life commented
> Андреееееей, забыл исходники в /src перекинуть, у тебя сейчас всё вместе в task_02.
> 
> А так проект запускается 👍

Ставьте лейбл Alien тем, кто группу не проставил 😁

2023-11-30 09:36 UTC, NogameNo-life approved these changes

2023-11-30 09:38 UTC, merged