[task_07] Add Lab_07
brstu/OOTPISP-2023 pull request #157
Opened 2023-11-27 16:03 UTC by ToxaChiter

2023-11-27 16:22 UTC, KARMA-143 approved these changes

2023-12-01 11:22 UTC, AlexaBailey requested changes
Убери partial при объявлении public partial class, исправь на public class

2023-12-01 14:34 UTC, ToxaChiter commented
> Убери partial при объявлении public partial class, исправь на public class

Это невозможно, проект просто не скомпилируется, так как WPF генерирует дополнительный код в таких же partial классах

2023-12-14 09:38 UTC, NogameNo-life approved these changes

2023-12-14 09:38 UTC, merged