[task_03] Lab 03
brstu/OOTPISP-2023 pull request #187
Opened 2023-11-29 09:59 UTC by Ian3707

2023-12-01 11:25 UTC, AlexaBailey commented on trunk/PO-9_210658/task-03/README.md
> +# Отчет по лабораторной работе №3
# Отчет по лабораторной работе №3 #

2023-12-01 11:28 UTC, AlexaBailey requested changes
Исправь README, несколько отметила, остальное аналогично,
```
##[space]Заголовок[space] ##
[blank line]
```

2023-12-01 11:28 UTC, AlexaBailey commented on trunk/PO-9_210658/task-03/README.md
> +## Контейнеры.
## Контейнеры ##

2023-12-01 11:28 UTC, AlexaBailey commented on trunk/PO-9_210658/task-03/README.md
> +## Вариант №9
## Вариант №9 ##

2023-12-01 11:28 UTC, AlexaBailey commented on trunk/PO-9_210658/task-03/README.md
> +## Цель работы
## Цель работы ##

2023-12-01 11:28 UTC, AlexaBailey commented on trunk/PO-9_210658/task-03/README.md
> +## Задания
## Задания ##

2023-12-05 07:09 UTC, Nenroin approved these changes
все работает и запускается

2023-12-21 08:22 UTC, ZakharTS approved these changes
Ничего не понял в шарпах, но вроде норм

2023-12-27 13:42 UTC, NogameNo-life approved these changes

2023-12-27 13:43 UTC, merged