[task_03]Lab3
brstu/OOTPISP-2023 pull request #231
Opened 2023-12-03 14:49 UTC by Papirosa225

2023-12-04 22:39 UTC, Nenroin reviewed
все оформлено правильно, но проект не запускается, исправляй
![изображение_2023-12-05_013925010](https://github.com/brstu/OOTPISP-2023/assets/96544191/e1d4218a-bfa5-4f2c-95ea-67bed63c4e7e)

2023-12-06 20:25 UTC, Papirosa225 commented
> все оформлено правильно, но проект не запускается, исправляй ![изображение_2023-12-05_013925010](https://private-user-images.githubusercontent.com/96544191/287862737-e1d4218a-bfa5-4f2c-95ea-67bed63c4e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTQ1ODcsIm5iZiI6MTcwMTg5NDI4NywicGF0aCI6Ii85NjU0NDE5MS8yODc4NjI3MzctZTFkNDIxOGEtYmZhNS00ZjJjLTk1ZWEtNjdiZWQ2M2M0ZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIwMjQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOTRmYzAyMTljYzZhODM1ZTZkNmIyN2ZmN2U5Y2Q4YTMxZGQ0NTc3YmI0ZGI5MzRjZDE4OTk2YmZiYTkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TGrBukZTDAdx1N2qnanPdsHcQcUZu5xJNlAOVd0EQCk)

Исправил,была багулина в CMAKE

2023-12-08 12:42 UTC, NogameNo-life requested changes

2023-12-08 12:42 UTC, NogameNo-life commented on trunk/PO-9_210669/Lab3/src/task06.h
> +
```suggestion
#include <sstream>

```

2023-12-13 17:56 UTC, NogameNo-life approved these changes

2023-12-13 17:56 UTC, merged