[task_08] Лабораторная работа №8
brstu/OOTPISP-2023 pull request #300
Opened 2023-12-16 16:09 UTC by peppemintu

2023-12-18 08:20 UTC, Nenroin reviewed
Ошибка
![изображение_2023-12-18_112043476](https://github.com/brstu/OOTPISP-2023/assets/96544191/2648e358-2855-4d12-86c0-5ba0328120cd)

2023-12-18 08:25 UTC, Nenroin approved these changes
Ну ладно ошибку выбрасывает, но работает.
![Uploading изображение_2023-12-18_112443044.png…]()

2023-12-20 09:55 UTC, NogameNo-life approved these changes

2023-12-20 12:29 UTC, NogameNo-life requested changes

2023-12-20 12:29 UTC, NogameNo-life commented on trunk/PO-9_210657/lab8/src/Builder.h
> +    }
```suggestion
```

2023-12-20 12:29 UTC, NogameNo-life commented on trunk/PO-9_210657/lab8/src/Builder.h
> +    virtual ~RobotBuilder() {}
```suggestion
    virtual ~RobotBuilder() = default;
```

2023-12-20 12:29 UTC, NogameNo-life commented on trunk/PO-9_210657/lab8/src/CMakeLists.txt
> +set(CMAKE_AUTORCC ON)
```suggestion
```

2023-12-20 12:29 UTC, NogameNo-life commented on trunk/PO-9_210657/lab8/src/CMakeLists.txt
> +find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)
```suggestion
```

2023-12-20 12:29 UTC, NogameNo-life commented on trunk/PO-9_210657/lab8/src/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
```suggestion
```

2023-12-21 07:57 UTC, NogameNo-life approved these changes

2023-12-21 07:57 UTC, merged