[task_01]
brstu/OOTPISP-2023 pull request #31
Opened 2023-10-09 18:53 UTC by Pandusss

[task_01] first attempt

2023-10-10 12:35 UTC, NogameNo-life requested changes
Не в тот каталог залили, посмотрите как у коллег. В каталоге trunk создаете свой личный каталог для всех лабораторных и называете его PO-(8 или 9)+номер зачетки/студенческого, дальше там отдельно будете добавлять каталоги с лабами. Подробнее в дискорде в General я писала. Для пул риквеста должна быть отдельная ветка, нельзя сразу из мастера, поэтому придется его закрыть.

2023-10-10 12:36 UTC, NogameNo-life commented
В каталоге tasks  содержатся только условия к лабораторным работам.

2023-10-11 11:30 UTC, NogameNo-life commented
Еще лейбл поставьте для вашей группы

2023-10-20 06:55 UTC, 11ALX11 commented
@Pandusss, эту ветку будешь закрывать? Просто у тебя есть другой пулл для первого таска

2023-10-20 06:59 UTC, closed without merging