[task_01] Лабораторная №1
brstu/OOTPISP-2023 pull request #32
Opened 2023-10-11 07:11 UTC by ZakharTS

2023-10-12 09:35 UTC, ZakharTS commented
Build and analyze так и так не проходит, можете просто смёржить в соответствии с required проверками?((

2023-10-12 10:00 UTC, ZakharTS commented
Он пытается скомпилить все проекты и ломается на папках с одинаковым названием (которые вообще не мои)💀💀💀

2023-10-12 12:25 UTC, NogameNo-life requested changes
Так CMakeLists надо модифицировать, зайди в trunk мастера и сделай по примеру, версию ставь 3.0.0. Перед всем этим обязательно пул.

2023-10-20 20:43 UTC, NogameNo-life approved these changes

2023-10-20 20:44 UTC, merged