[task_01]lab1
brstu/OOTPISP-2023 pull request #45
Opened 2023-10-13 07:13 UTC by ProstoMyk

2023-10-13 13:23 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
Версия cmake должна быть установлена 3.0.0

2023-10-13 13:25 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +project(PERVOLABCMAKE VERSION 0.1 LANGUAGES CXX)
Название проекта PERVOLABCMAKE во всей конфигурации заменить на po9_210665_task_01
(Ctrl+F -> заменить всё)

2023-10-13 13:25 UTC, Dashubaa commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
Сам же ставил!

2023-10-13 13:26 UTC, Dashubaa commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
Согласна

2023-10-13 13:41 UTC, ZakharTS requested changes

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/gg.cpp
> +    this->setWindowTitle("Huiii");
Переименовать название окна

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +project(PERVOLABCMAKE VERSION 0.1 LANGUAGES CXX)
Название проекта PERVOLABCMAKE во всей конфигурации заменить на po9_210665_task_01
(Ctrl+F -> заменить всё)
((на будущее))

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/gg.h
> +#include "QByteArray"
Импорт сторонних библиотек принято делать через треугольные скобки #include <QByteArray>, в кавычках - собственные заголовки

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/mainwindow.h
> +#include "QPlainTextEdit"
Аналогично

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/mainwindow.h
> +    QPlainTextEdit* txtEdit;
Поля класса должны быть приватными

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
```suggestion
cmake_minimum_required(VERSION 3.0.0)
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +project(PERVOLABCMAKE VERSION 0.1 LANGUAGES CXX)
```suggestion
project(po9_210665_task_01 VERSION 0.1 LANGUAGES CXX)
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +    qt_add_executable(PERVOLABCMAKE
```suggestion
    qt_add_executable(po9_210665_task_01
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +        add_library(PERVOLABCMAKE SHARED
```suggestion
        add_library(po9_210665_task_01 SHARED
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +        add_executable(PERVOLABCMAKE
```suggestion
        add_executable(po9_210665_task_01
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +target_link_libraries(PERVOLABCMAKE PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
```suggestion
target_link_libraries(po9_210665_task_01 PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +set_target_properties(PERVOLABCMAKE PROPERTIES
```suggestion
set_target_properties(po9_210665_task_01 PROPERTIES
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +install(TARGETS PERVOLABCMAKE
```suggestion
install(TARGETS po9_210665_task_01
```

2023-10-13 13:41 UTC, ZakharTS commented on trunk/PO-9_210665/task_01/src/CMakeLists.txt
> +    qt_finalize_executable(PERVOLABCMAKE)
```suggestion
    qt_finalize_executable(po9_210665_task_01)
```

2023-10-18 08:04 UTC, ZakharTS approved these changes

2023-10-20 06:56 UTC, Dashubaa requested changes

2023-10-20 06:56 UTC, Dashubaa commented on trunk/PO-9_210665/task_01/images/vyp2_2.png
название окна это то как я могу описать твою работу. Измени и изменится мое отношение к ней.

2023-10-20 07:29 UTC, Dashubaa approved these changes
норм

2023-10-20 18:51 UTC, NogameNo-life requested changes
CMake  переписать, этот только для Qt Creator

2023-10-20 20:46 UTC, NogameNo-life requested changes
CMake как в мастере перепиши

2023-10-21 07:21 UTC, 11ALX11 commented on README.md
> +|16|Николайчик Николай | [ProstoMyk](https://github.com/ProstoMyk) | 210665 | :white_check_mark: | :white_check_mark: |||||||||
Присоединяйся в секту, указывающую ссылку на папку в порядковом номере

```suggestion
|[16](./trunk/PO-9_210665)|Николайчик Николай | [ProstoMyk](https://github.com/ProstoMyk) | 210665 | :white_check_mark: | :white_check_mark: |||||||||
```

2023-10-21 10:55 UTC, ZakharTS requested changes

2023-10-21 13:29 UTC, ZakharTS approved these changes

2023-10-21 17:51 UTC, NogameNo-life requested changes

2023-10-21 17:51 UTC, NogameNo-life commented on README.md
> +|[16](./trunk/PO-9_210665)|Николайчик Николай | [ProstoMyk](https://github.com/ProstoMyk) | 210665 | :white_check_mark: | :white_check_mark: |||||||||
```suggestion
|16|Николайчик Николай | [ProstoMyk](https://github.com/ProstoMyk) | [210665](./trunk/PO-9_210665) | :white_check_mark: | :white_check_mark: |||||||||
```

2023-11-01 06:36 UTC, NogameNo-life approved these changes

2023-11-03 08:39 UTC, 11ALX11 approved these changes

2023-11-08 09:09 UTC, merged