[task_01]lab_1
brstu/OOTPISP-2023 pull request #53
Opened 2023-10-16 06:24 UTC by Vodemus

2023-10-20 08:28 UTC, NogameNo-life requested changes
CMake надо поправить, автосгенерированный Qt Creator не соберет VS. Посмотрите как в мастере.

2023-10-27 06:23 UTC, NogameNo-life requested changes

2023-10-27 06:23 UTC, NogameNo-life commented on README.md
> +|[18](./trunk/PO-9_210667/)|Оводок Вадим | [Vodemus](https://github.com/Vodemus) | 210667 | :white_check_mark: | :white_check_mark: |||||||||
```suggestion
|18|Оводок Вадим | [Vodemus](https://github.com/Vodemus) | (210667 )(./trunk/PO-9_210667/)| :white_check_mark: | :white_check_mark: |||||||||
```

2023-10-27 07:48 UTC, Vodemus commented on trunk/PO-9_210667/task_01/src/CMakeLists.txt
> +endif()
```suggestion
cmake_minimum_required(VERSION 3.5)

project(untitled9 VERSION 0.1 LANGUAGES CXX)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_PREFIX_PATH $ENV{QTDIR})

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Widgets)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets)

add_executable(po9_210667_lab1
        main.cpp
        widget.cpp
        widget.h
        widget.ui
)


target_link_libraries(po9_210667_lab1 Qt${QT_VERSION_MAJOR}::Widgets)

```

2023-10-27 07:52 UTC, 11ALX11 reviewed
Фикс для авто сгенерированного

2023-10-27 07:52 UTC, 11ALX11 commented on trunk/PO-9_210667/task_01/src/widget.h
> +#endif // WIDGET_H
```suggestion
#ifndef WIDGET_H
#define WIDGET_H

#include <QWidget> //210667

QT_BEGIN_NAMESPACE
namespace Ui { class Widget; } //210667
QT_END_NAMESPACE

class Widget : public QWidget //210667
{ //210667
    Q_OBJECT

public: //210667
    Widget(QWidget *parent = nullptr); //210667
    ~Widget(); //210667

private: //210667
    Ui::Widget *ui; //210667
};
#endif // WIDGET_H
```

2023-11-01 07:08 UTC, NogameNo-life requested changes
Удали CMakeLists.txt.user

2023-11-08 09:17 UTC, merged