Labs_1_po9
brstu/OOTPISP-2023 pull request #6
Opened 2023-09-22 07:50 UTC by dkachalovskiy

2023-09-26 08:25 UTC, NogameNo-life requested changes

2023-09-26 08:25 UTC, NogameNo-life commented on trunk/ПО-9.210656/lab1/readme.md
> +В данной лабораторной работе были изучены одни из основных элементов графического интерфейса, а именно `QLabel, QSpinBox, QSlider, QPlainTextEdit`. Так же были изучены основы взаимодействия слотов и
По отчету непонятно, что в итоге было сделано по лабе, отчет должен походить больше на документацию к коду.

2023-09-29 06:33 UTC, NogameNo-life requested changes
Каталоги кириллицей не называтьть и у вас некоторые файлы дублируются из-за чего duplication не проходит.

2023-09-29 06:33 UTC, NogameNo-life commented on trunk/ПО-9.210656/lab1/readme.md
> +В данной лабораторной работе были изучены одни из основных элементов графического интерфейса, а именно `QLabel, QSpinBox, QSlider, QPlainTextEdit`. Так же были изучены основы взаимодействия слотов и
https://github.com/brstu/GIIS-2023/tree/master/trunk/ii200103 Сделайте что-то подобное.

2023-10-03 14:02 UTC, NogameNo-life requested changes
CMakeLists.txt добавить для сборки.

2023-10-03 14:27 UTC, dkachalovskiy commented
Я начинал делать проект под qmake. и файл для qmake как раз присутствует. _lab.pro_. нужно все переписывать под стандарт CMake?

2023-10-04 08:56 UTC, NogameNo-life commented
> Я начинал делать проект под qmake. и файл для qmake как раз присутствует. _lab.pro_. нужно все переписывать под стандарт CMake?

Да, CMake более универсальная система. Там небольшой файл получится.

2023-10-06 05:58 UTC, NogameNo-life approved these changes

2023-10-10 10:18 UTC, merged