[doc] add doc task 07
brstu/OOTPISP-2023 pull request #66
Opened 2023-10-28 13:58 UTC by 11ALX11

2023-10-28 15:41 UTC, 11ALX11 commented on tasks/task_07/README.md
> +﻿# Лабораторная работа № 13
```suggestion
﻿# Лабораторная работа № 7
```

2023-10-28 15:41 UTC, 11ALX11 commented on tasks/task_07/README.md
> +﻿# Лабораторная работа № 13
Забыл...

2023-10-30 07:39 UTC, NogameNo-life requested changes
Используй для формул math mode https://github.blog/2022-05-19-math-support-in-markdown/

2023-11-10 05:58 UTC, NogameNo-life approved these changes

2023-11-17 07:29 UTC, merged