[task_02] lab2
brstu/OOTPISP-2023 pull request #67
Opened 2023-10-28 17:50 UTC by ProstoMyk

2023-10-28 19:34 UTC, 11ALX11 commented on trunk/PO-9_210665/task_02/README.md
> +это прекрасно и хотя бы не пахнет winAPI.
Коляяяяя, новая строка в конце файла
```suggestion
это прекрасно и хотя бы не пахнет winAPI.

```

2023-10-28 19:35 UTC, 11ALX11 commented on trunk/PO-9_210665/task_02/README.md
> +это прекрасно и хотя бы не пахнет winAPI.
<img width="458" alt="image" src="https://github.com/brstu/OOTPISP-2023/assets/91539438/ad9b0036-dda0-4668-999d-4d39f84243e6">

2023-10-28 19:41 UTC, 11ALX11 commented
А прикол

Новой строки нет

2023-10-28 19:45 UTC, ProstoMyk commented
да вроде и есть строка в конце

2023-11-10 07:01 UTC, 11ALX11 approved these changes

2023-11-19 21:48 UTC, NogameNo-life requested changes
В файле texteditor.cpp заменить setFilename на  setfila

2023-11-19 21:48 UTC, NogameNo-life commented on trunk/PO-9_210665/task_02/src/main.cpp
> +#include "Textid.h" //210665
```suggestion
#include "texteditor.h" //210665
```

2023-11-19 21:48 UTC, NogameNo-life commented on trunk/PO-9_210665/task_02/src/texteditor.cpp
> +#include "Textid.h"
```suggestion
#include "texteditor.h"
```

2023-11-21 17:15 UTC, HeyJIOBUM reviewed
Посмотри на файлы в add_executable

2023-11-22 11:42 UTC, NogameNo-life requested changes

2023-11-22 11:42 UTC, NogameNo-life commented on trunk/PO-9_210665/task_02/src/CMakeLists.txt
> +project(TextEditor VERSION 2023.10.04.0 LANGUAGES CXX)
```suggestion
project(TextEditor LANGUAGES CXX)
```

2023-11-22 11:42 UTC, NogameNo-life commented on trunk/PO-9_210665/task_02/src/CMakeLists.txt
> +        Textid.cpp
```suggestion
        texteditor.cpp
```

2023-11-22 11:42 UTC, NogameNo-life commented on trunk/PO-9_210665/task_02/src/CMakeLists.txt
> +        Textid.h
```suggestion
        texteditor.h
```

2023-11-24 06:35 UTC, HeyJIOBUM reviewed
⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠛⠛⠋⠉⠈⠉⠉⠉⠉⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢿⣿⣿⣿⣿
⣿⣿⣿⣿⡏⣀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿
⣿⣿⣿⢏⣴⣿⣷⠀⠀⠀⠀⠀⢾⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿
⣿⣿⣟⣾⣿⡟⠁⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣷⢢⠀⠀⠀⠀⠀⠀⠀⢸⣿
⣿⣿⣿⣿⣟⠀⡴⠄⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⣿
⣿⣿⣿⠟⠻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠶⢴⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⣿
⣿⣁⡀⠀⠀⢰⢠⣦⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣿⡄⠀⣴⣶⣿⡄⣿
⣿⡋⠀⠀⠀⠎⢸⣿⡆⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⠗⢘⣿⣟⠛⠿⣼
⣿⣿⠋⢀⡌⢰⣿⡿⢿⡀⠀⠀⠀⠀⠀⠙⠿⣿⣿⣿⣿⣿⡇⠀⢸⣿⣿⣧⢀⣼
⣿⣿⣷⢻⠄⠘⠛⠋⠛⠃⠀⠀⠀⠀⠀⢿⣧⠈⠉⠙⠛⠋⠀⠀⠀⣿⣿⣿⣿⣿
⣿⣿⣧⠀⠈⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠟⠀⠀⠀⠀⢀⢃⠀⠀⢸⣿⣿⣿⣿
⣿⣿⡿⠀⠴⢗⣠⣤⣴⡶⠶⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡸⠀⣿⣿⣿⣿
⣿⣿⣿⡀⢠⣾⣿⠏⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠉⠀⣿⣿⣿⣿
⣿⣿⣿⣧⠈⢹⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿
⣿⣿⣿⣿⡄⠈⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣦⣄⣀⣀⣀⣀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

2023-11-24 06:56 UTC, NogameNo-life approved these changes

2023-11-24 07:01 UTC, merged