add task_05
brstu/OOTPISP-2023 pull request #7
Opened 2023-09-22 09:39 UTC by Mkrshkk

2023-09-24 20:58 UTC, NogameNo-life requested changes

2023-09-24 20:58 UTC, NogameNo-life commented on tasks/task_05/README.md
> +### Цель работы:
```suggestion
## Создание приложений баз данных

### Цель работы
```

2023-09-24 20:58 UTC, NogameNo-life commented on tasks/task_05/README.md
> +Задание
```suggestion
### Задание
```

2023-09-24 20:58 UTC, NogameNo-life commented on tasks/task_05/README.md
> +        <td>Напишите программу «Учет загруженности классов» (5 классов). В программе использовать две таблицы: klass (поля id, nom, para) и uses (поля id, dissiplina). Создать запросы: определить нез
```suggestion
        <td>Напишите программу «Учет загруженности классов» (5 классов). В программе использовать две таблицы: klass (поля ***id, nom, para***) и uses (поля ***id, dissiplina***). Создать запросы: определить незагруженные классы в определенный день; вывести таблицу загруженности классов за заданный день.</td>
```

2023-09-24 20:58 UTC, NogameNo-life commented on tasks/task_05/README.md
> +        <td>Напишите программу «Учет загруженности классов» (5 классов). В программе использовать две таблицы: klass (поля id, nom, para) и uses (поля id, dissiplina). Создать запросы: определить нез
Я бы как-нибудь выделила названия полей

2023-09-29 12:00 UTC, NogameNo-life approved these changes

2023-10-03 05:40 UTC, ToxaChiter approved these changes
Под пиво пойдёт

2023-10-03 11:43 UTC, merged