[doc] Add Lab_04
brstu/OOTPISP-2023 pull request #8
Opened 2023-09-22 11:28 UTC by ToxaChiter

2023-09-24 20:30 UTC, NogameNo-life requested changes

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +
```suggestion
```

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +1.	Какие возможности предоставляет среда быстрой разработки приложений `Qt designer`. Чем она отличается от других аналогичных программ?
```suggestion

1.	Какие возможности предоставляет среда быстрой разработки приложений `Qt designer`. Чем она отличается от других аналогичных программ?
```

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +```C++
```suggestion

```C++ 
```

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +```C++
```suggestion

```C++ 
```

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +```C++
```suggestion

```C++ 
```

2023-09-24 20:30 UTC, NogameNo-life commented on tasks/task_04/readme.md
> +Первый параметр указывает на номер строки, второй – на номер столбца. Для записи числа `k` в `(i,j)` ячейку таблицы `table` его необходимо преобразовать к типу `QString`:
```suggestion

Первый параметр указывает на номер строки, второй – на номер столбца. Для записи числа `k` в `(i,j)` ячейку таблицы `table` его необходимо преобразовать к типу `QString`:
```

2023-09-29 12:01 UTC, NogameNo-life approved these changes

2023-10-03 05:46 UTC, AlexaBailey approved these changes
Well Done!

2023-10-03 11:42 UTC, merged