[task_01]
brstu/OOTPISP-2023 pull request #83
Opened 2023-11-10 08:04 UTC by nikalow1

2023-11-10 08:23 UTC, NogameNo-life requested changes

2023-11-10 08:23 UTC, NogameNo-life commented on trunk/PO-9_210663/task_01/src/CMakeLists.txt
> +add_executable(untitled5
```suggestion
add_executable(po9_210663_task_01
```

2023-11-10 08:23 UTC, NogameNo-life commented on trunk/PO-9_210663/task_01/src/CMakeLists.txt
> +target_link_libraries(untitled5 Qt${QT_VERSION_MAJOR}::Widgets)
```suggestion
target_link_libraries(po9_210663_task_01 Qt${QT_VERSION_MAJOR}::Widgets)
```

2023-11-10 08:25 UTC, 11ALX11 commented on trunk/PO-9_210663/task_01/src/CMakeLists.txt
> +project(untitled5  LANGUAGES CXX)
```suggestion
project(po9_210663_task_01 LANGUAGES CXX)
```

2023-11-19 21:08 UTC, NogameNo-life approved these changes

2023-11-19 21:22 UTC, merged