[task_02] Lab2
brstu/OOTPISP-2023 pull request #85
Opened 2023-11-12 14:58 UTC by Pandusss

add lab2

2023-11-13 09:59 UTC, Pandusss commented
Забыл добавить себе галочку в readme, закоммичу со следующей работой.

2023-11-13 11:09 UTC, Nenroin approved these changes

2023-11-13 13:31 UTC, NogameNo-life requested changes
CMake переделать, .gitignore удалить, таблицу выровнять как было

2023-11-13 14:27 UTC, Pandusss commented
CMake поправил, gitignore удалил, таблицу выравнял

2023-11-17 08:21 UTC, NogameNo-life approved these changes

2023-11-17 18:38 UTC, Nenroin approved these changes
Еще раз апруваю

2023-11-19 20:58 UTC, NogameNo-life requested changes

2023-11-19 20:58 UTC, NogameNo-life commented on trunk/PO-9_210655/task_02/src/CMakeLists.txt
> +set(PROJECT_SOURCES
```suggestion
add_executable(PROJECT_SOURCES
```

2023-11-19 20:58 UTC, NogameNo-life commented on trunk/PO-9_210655/task_02/src/CMakeLists.txt
> +target_link_libraries(lab9 PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
```suggestion
target_link_libraries(PROJECT_SOURCES PRIVATE Qt${QT_VERSION_MAJOR}::Widgets)
```

2023-11-19 20:58 UTC, NogameNo-life commented on trunk/PO-9_210655/task_02/src/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
```suggestion
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_PREFIX_PATH $ENV{QTDIR})
```

2023-11-19 20:58 UTC, NogameNo-life commented on trunk/PO-9_210655/task_02/src/main.cpp
> +    return app.exec();
```suggestion
    ww.show();
    return a.exec();
```

2023-11-19 20:59 UTC, NogameNo-life requested changes

2023-11-19 20:59 UTC, NogameNo-life commented on README.md
> +|6|Зеленков Константин |[Pandus](https://github.com/Pandusss)|210655|:white_check_mark:|:white_check_mark:|:white_check_mark:||||||||
```suggestion
|6|Зеленков Константин |[Pandus](https://github.com/Pandusss)|[210655](./trunk/PO-9_210655/)|:white_check_mark:|:white_check_mark:|:white_check_mark:||||||||
```

2023-11-20 10:54 UTC, 11ALX11 reviewed
рестарт codacy проверку

2023-11-20 10:54 UTC, 11ALX11 commented on trunk/PO-9_210655/task_02/README.md
> +Было создано приложение Qt, реализующее базовый функционал текстового редактора windows.
```suggestion
Было создано приложение Qt, реализующее базовый функционал текстового редактора windows .
```

2023-11-20 10:54 UTC, 11ALX11 commented
> рестарт codacy проверку

<img width="977" alt="image" src="https://github.com/brstu/OOTPISP-2023/assets/91539438/a8a56fe8-74fc-4d91-b92c-f85832506daa">

2023-11-20 11:00 UTC, 11ALX11 commented
оке, он походу повис.

Мой пулл [103] даже не видит

2023-11-22 08:54 UTC, NogameNo-life approved these changes

2023-11-22 08:58 UTC, merged