[task_01] Lab1
brstu/OOTPISP-2023 pull request #88
Opened 2023-11-17 07:55 UTC by YaroslavKuchko26

2023-11-17 08:05 UTC, Nenroin approved these changes
НОРМАЛЬНО

2023-11-21 16:37 UTC, HeyJIOBUM requested changes
Добавь пустую строку в конец readme

2023-11-27 09:28 UTC, NogameNo-life commented
> НОРМАЛЬНО

Неа, изменения затрагивают чужой каталог, плохое ревью

2023-11-27 09:32 UTC, NogameNo-life requested changes
Не должно быть изменений в PO-9_210669

2023-12-01 07:20 UTC, closed without merging